[project]
name = "ai-startup-investment-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yeonje Park", email = "yeonje1004@naver.com" }
]
requires-python = ">=3.11.11"
dependencies = [
    "faiss-cpu>=1.15.1",
    "langchain>=1.4.3",
    "langchain-community>=0.4.2",
    "langchain-huggingface>=1.2.2",
    "langchain-openai>=1.6.6",
    "langchain-tavily>=0.2.18",
    "langchain-text-splitters>=1.1.2",
    "langgraph>=1.2.12",
    "pydantic>=2.13.5",
    "pymupdf>=1.28.2",
    "python-dotenv>=1.2.3",
    "sentence-transformers>=6.1.0",
]

[project.scripts]
ai-startup-investment-agent = "ai_startup_investment_agent:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
